import "@mantine/core/styles.css";
import { MaintineProviderWrapper } from "@/providers/MaintineProviderWrapper";
import TanstackProvider from "@/providers/TanstackProvider";
import { ColorSchemeScript } from "@mantine/core";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next | Tanstack | Maintine",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript defaultColorScheme="auto" />
      </head>
      <body className={inter.className} suppressHydrationWarning={true}>
        <TanstackProvider>
          <MaintineProviderWrapper>{children}</MaintineProviderWrapper>
        </TanstackProvider>
      </body>
    </html>
  );
}
